# Generated by Django 5.0.6 on 2024-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                help_text="Введите слаг", unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
