# Generated by Django 5.0.6 on 2024-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Введите страну",
                        max_length=100,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "INN",
                    models.CharField(
                        help_text="Введите ИНН", max_length=100, verbose_name="ИНН"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Введите адрес отделения",
                        verbose_name="Адрес отделения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["country"],
            },
        ),
    ]
