# Generated by Django 5.0.6 on 2024-05-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя", max_length=100, verbose_name="Имя"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите контактный телефон",
                        max_length=255,
                        verbose_name="Контактный телефон",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Введите адрес отделения",
                        verbose_name="Адрес отделения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name"],
            },
        ),
    ]
