# Generated by Django 5.0.6 on 2024-06-04 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Укажите дату создания",
                verbose_name="Дата создания записи",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Укажите дату последнего изменения",
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
