# Generated by Django 5.0.6 on 2024-06-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Признак публикации",
                verbose_name="Опубликовано",
            ),
        ),
    ]
