# Generated by Django 5.0.6 on 2024-06-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at", "-updated_at", "name", "price", "category"],
                "permissions": [
                    ("change_published", "Может менять признак публикации продукта"),
                    ("change_description", "Может менять описание продукта"),
                    ("change_category", "Может менять категорию продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
